# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'LTChatDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LTChatDemo
  #     pod 'XMPPFramework', '~> 3.7.0'
  #     pod 'GoogleWebRTC'

    pod 'LTChat'
    pod 'JSQMessagesViewController'    
end
