# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'LTChatDemo' do
    pod 'JSQMessagesViewController'
    pod 'XMPPFramework', '~> 3.7.0'
    pod 'GoogleWebRTC'
end
